# Generated by Django 6.1.1 on 2026-09-03 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_add_faculty_and_people"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="attended_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
