# Generated by Django 6.1.1 on 2026-09-03 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_reservation_attendees"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_attendees",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
    ]
