# Generated by Django 5.2.10 on 2026-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='estado',
        ),
        migrations.AddField(
            model_name='sala',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
