# Generated by Django 6.1 on 2026-08-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_remove_sala_estado_sala_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='capacidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
