# Generated by Django 6.1 on 2026-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_sala_capacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='tipo',
            field=models.CharField(choices=[('estudio', 'Aula de estudio'), ('sala', 'Sala'), ('conferencia', 'Sala de conferencias'), ('auditorio', 'Auditorio')], default='sala', max_length=20),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
